#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

echo "Tests started at…"
date "+%H:%M:%S"

# GC customizations
export RUBY_GC_MALLOC_LIMIT=79000000
export RUBY_HEAP_MIN_SLOTS=800000
export RUBY_HEAP_FREE_MIN=100000
export RUBY_HEAP_SLOTS_INCREMENT=400000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1

# setup environment
RAILS_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export RAILS_ROOT
export RAILS_ENV="test"
export RACK_ROOT="$RAILS_ROOT"
export RACK_ENV="$RAILS_ENV"

test -d "/usr/share/rbenv/shims" && {
  export PATH=/usr/share/rbenv/shims:$PATH
}
export RBENV_VERSION="2.1.6"

export PATH="$RACK_ROOT/bin:$PATH"

# run tests
echo "Running tests …"
date "+%H:%M:%S"

# run tests.
script/test
