#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

script/bootstrap

echo "==> Updating db..."
# run all database migrations to ensure everything is up to date.
bin/rake db:create db:migrate
